In [ ]:
# 방문지 정보 데이터 전처리

In [38]:
import pandas as pd

In [100]:
file_path = r"E:\AI_HUB\data\Training\labeled_data\TL_csv\tn_visit_area_info_방문지정보_H.csv"

tn_visit_area_info = pd.read_csv(file_path)

tn_visit_area_info

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
0,2306030001,e_e000295,1,집,2023-06-03,2023-06-03,경기 성남시 분당구 수내로 39,경기 성남시 분당구 수내동 1-1,NaN,NaN,...,NaN,NaN,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2306030002,e_e000295,2,트레이더스 홀세일 클럽 안산점,2023-06-03,2023-06-03,경기 안산시 단원구 중앙대로 397,경기 안산시 단원구 신길동 1687,126.785016,37.331252,...,트레이더스홀세일클럽 안산점,90.0,4,N,6.0,NaN,5.0,3.0,5.0,NaN
2,2306030003,e_e000295,3,백령 할인마트,2023-06-03,2023-06-03,인천 옹진군 영흥면 영흥로 164-10,인천 옹진군 영흥면 내리 8-31,126.493973,37.258358,...,백령할인마트,30.0,4,N,9.0,NaN,5.0,3.0,5.0,NaN
3,2306030007,e_e000295,4,아침 풍경펜션,2023-06-03,2023-06-04,인천 옹진군 영흥면 영흥서로380번길 101-3,인천 옹진군 영흥면 내리 1212-32,NaN,NaN,...,아침풍경펜션,540.0,24,N,6.0,3.0,5.0,5.0,5.0,NaN
4,2306040001,e_e000295,5,사이 바다,2023-06-04,2023-06-04,인천 옹진군 영흥면 영흥북로 374-25,인천 옹진군 영흥면 내리 724-132,NaN,NaN,...,하이바다,60.0,4,N,1.0,NaN,3.0,1.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46004,2309220002,h_h006874,2,꼬스뗀뇨,2023-09-22,2023-09-22,제주특별자치도 제주시 구좌읍 해맞이해안로 2080,제주특별자치도 제주시 구좌읍 종달리 150,126.905244,33.509868,...,꼬스뗀뇨,60.0,3,N,1.0,NaN,3.0,2.0,2.0,NaN
46005,2309220003,h_h006874,3,마이 피기 팬트리,2023-09-22,2023-09-22,제주특별자치도 제주시 구좌읍 하도13길 6,제주특별자치도 제주시 구좌읍 하도리 1091-5,126.888132,33.508700,...,마이피기팬트리,30.0,10,N,2.0,NaN,4.0,4.0,4.0,NaN
46006,2309220004,h_h006874,4,월정리 해수욕장,2023-09-22,2023-09-22,NaN,제주특별자치도 제주시 구좌읍 월정리 33-3,126.795805,33.556469,...,월정리해수욕장,120.0,1,Y,11.0,NaN,4.0,4.0,4.0,NaN
46007,2309220005,h_h006874,5,민경이네어등포해녀촌,2023-09-22,2023-09-22,제주특별자치도 제주시 구좌읍 해맞이해안로 830,제주특별자치도 제주시 구좌읍 행원리 102,126.825773,33.553735,...,민경이네어등포해녀촌,30.0,11,N,2.0,NaN,4.0,4.0,4.0,NaN
46008,2309220006,h_h006874,6,김정 문화회관,2023-09-22,2023-09-23,제주특별자치도 서귀포시 김정문화로 36,제주특별자치도 서귀포시 강정동 176,126.508654,33.251086,...,김정문화회관,240.0,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
# 데이터 타입 변환
# tn_visit_area_info['VISIT_AREA_ID'] = tn_visit_area_info['VISIT_AREA_ID'].astype(str)
# tn_visit_area_info['VISIT_START_YMD'] = pd.to_datetime(tn_visit_area_info['VISIT_START_YMD'])
# tn_visit_area_info['VISIT_END_YMD'] = pd.to_datetime(tn_visit_area_info['VISIT_END_YMD'])
# tn_visit_area_info['VISIT_AREA_TYPE_CD'] = tn_visit_area_info['VISIT_AREA_TYPE_CD'].astype(str)
# tn_visit_area_info['VISIT_CHC_REASON_CD'] = tn_visit_area_info['VISIT_CHC_REASON_CD'].astype(str)
# tn_visit_area_info['LODGING_TYPE_CD'] = tn_visit_area_info['LODGING_TYPE_CD'].astype(str)
# tn_visit_area_info['SGG_CD'] = tn_visit_area_info['SGG_CD'].astype(str)

In [102]:
# 제주특별자치도만 필터링

tn_visit_area_info = tn_visit_area_info[tn_visit_area_info['ROAD_NM_ADDR'].str.contains("제주", na=False)]
tn_visit_area_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23794 entries, 2413 to 46008
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   VISIT_AREA_ID        23794 non-null  object
 1   TRAVEL_ID            23794 non-null  object
 2   VISIT_ORDER          23794 non-null  int64
 3   VISIT_AREA_NM        23794 non-null  object
 4   VISIT_START_YMD      23794 non-null  datetime64[ns]
 5   VISIT_END_YMD        23794 non-null  datetime64[ns]
 6   ROAD_NM_ADDR         23794 non-null  object
 7   LOTNO_ADDR           23420 non-null  object
 8   X_COORD              22854 non-null  float64
 9   Y_COORD              22854 non-null  float64
 10  ROAD_NM_CD           175 non-null    float64
 11  LOTNO_CD             175 non-null    float64
 12  POI_ID               22896 non-null  object
 13  POI_NM               22896 non-null  object
 14  RESIDENCE_TIME_MIN   23675 non-null  float64
 15  VISIT_AREA_TYPE_CD   23794 non-null  object
 16  REVISIT_YN           23455 non-null  object
 17  VISIT_CHC_REASON_CD  23794 non-null  object
 18  LODGING_TYPE_CD      23794 non-null  object
 19  DGSTFN               23453 non-null  float64
 20  REVISIT_INTENTION    23453 non-null  float64
 21  RCMDTN_INTENTION     23453 non-null  float64
 22  SGG_CD               23794 non-null  object
dtypes: datetime64[ns](2), float64(8), int64(1), object(12)
memory usage: 4.4+ MB

In [103]:
tn_visit_area_info.isnull().sum()

VISIT_AREA_ID              0
TRAVEL_ID                  0
VISIT_ORDER                0
VISIT_AREA_NM              0
VISIT_START_YMD            0
VISIT_END_YMD              0
ROAD_NM_ADDR               0
LOTNO_ADDR               374
X_COORD                  940
Y_COORD                  940
ROAD_NM_CD             23619
LOTNO_CD               23619
POI_ID                   898
POI_NM                   898
RESIDENCE_TIME_MIN       119
VISIT_AREA_TYPE_CD         0
REVISIT_YN               339
VISIT_CHC_REASON_CD        0
LODGING_TYPE_CD            0
DGSTFN                   341
REVISIT_INTENTION        341
RCMDTN_INTENTION         341
SGG_CD                     0
dtype: int64

In [104]:
# null값 많은 열 우선 제거
columns_to_drop = ['ROAD_NM_CD', 'LOTNO_CD']

tn_visit_area_info_c = tn_visit_area_info.drop(columns=columns_to_drop)

# 결과 확인
tn_visit_area_info_c.isnull().sum()

VISIT_AREA_ID            0
TRAVEL_ID                0
VISIT_ORDER              0
VISIT_AREA_NM            0
VISIT_START_YMD          0
VISIT_END_YMD            0
ROAD_NM_ADDR             0
LOTNO_ADDR             374
X_COORD                940
Y_COORD                940
POI_ID                 898
POI_NM                 898
RESIDENCE_TIME_MIN     119
VISIT_AREA_TYPE_CD       0
REVISIT_YN             339
VISIT_CHC_REASON_CD      0
LODGING_TYPE_CD          0
DGSTFN                 341
REVISIT_INTENTION      341
RCMDTN_INTENTION       341
SGG_CD                   0
dtype: int64

In [105]:
# null이 있는 데이터의 방문지명 확인 -> 무의미한 장소들

columns_to_check = ['REVISIT_YN', 'DGSTFN', 'REVISIT_INTENTION', 'RCMDTN_INTENTION']
null_rows = tn_visit_area_info[tn_visit_area_info[columns_to_check].isnull().any(axis=1)]

null_places = null_rows['VISIT_AREA_NM'].drop_duplicates()
null_places

2413               집
3051     제주 건입 현대아파트
11571           가족 집
11576    제주시 고마로 14길
11750        카페이나 사리
            ...
45794           친구 집
45841         로마인 펜션
45906         셀프 빨래방
45976           전원주택
46008        김정 문화회관
Name: VISIT_AREA_NM, Length: 77, dtype: object

In [106]:
# 의미 없는 행 삭제

tn_visit_area_info = tn_visit_area_info.dropna(subset=columns_to_check)
tn_visit_area_info.isnull().sum()

VISIT_AREA_ID              0
TRAVEL_ID                  0
VISIT_ORDER                0
VISIT_AREA_NM              0
VISIT_START_YMD            0
VISIT_END_YMD              0
ROAD_NM_ADDR               0
LOTNO_ADDR               283
X_COORD                  712
Y_COORD                  712
ROAD_NM_CD             23452
LOTNO_CD               23452
POI_ID                   670
POI_NM                   670
RESIDENCE_TIME_MIN         0
VISIT_AREA_TYPE_CD         0
REVISIT_YN                 0
VISIT_CHC_REASON_CD        0
LODGING_TYPE_CD            0
DGSTFN                     0
REVISIT_INTENTION          0
RCMDTN_INTENTION           0
SGG_CD                     0
dtype: int64

In [107]:
# 필요 없는 열 제거
columns_to_drop = ['ROAD_NM_CD', 'LOTNO_CD']

tn_visit_area_info = tn_visit_area_info.drop(columns=columns_to_drop)

# 결과 확인
tn_visit_area_info.isnull().sum()

VISIT_AREA_ID            0
TRAVEL_ID                0
VISIT_ORDER              0
VISIT_AREA_NM            0
VISIT_START_YMD          0
VISIT_END_YMD            0
ROAD_NM_ADDR             0
LOTNO_ADDR             283
X_COORD                712
Y_COORD                712
POI_ID                 670
POI_NM                 670
RESIDENCE_TIME_MIN       0
VISIT_AREA_TYPE_CD       0
REVISIT_YN               0
VISIT_CHC_REASON_CD      0
LODGING_TYPE_CD          0
DGSTFN                   0
REVISIT_INTENTION        0
RCMDTN_INTENTION         0
SGG_CD                   0
dtype: int64

In [108]:
columns_to_drop = ['LOTNO_ADDR']

tn_visit_area_info = tn_visit_area_info.drop(columns=columns_to_drop)

# 결과 확인
tn_visit_area_info.isnull().sum()

VISIT_AREA_ID            0
TRAVEL_ID                0
VISIT_ORDER              0
VISIT_AREA_NM            0
VISIT_START_YMD          0
VISIT_END_YMD            0
ROAD_NM_ADDR             0
X_COORD                712
Y_COORD                712
POI_ID                 670
POI_NM                 670
RESIDENCE_TIME_MIN       0
VISIT_AREA_TYPE_CD       0
REVISIT_YN               0
VISIT_CHC_REASON_CD      0
LODGING_TYPE_CD          0
DGSTFN                   0
REVISIT_INTENTION        0
RCMDTN_INTENTION         0
SGG_CD                   0
dtype: int64

In [109]:
columns_to_check_POI = ['POI_ID', 'POI_NM']
null_rows = tn_visit_area_info[tn_visit_area_info[columns_to_check_POI].isnull().any(axis=1)]

null_places = null_rows[['VISIT_AREA_NM', 'ROAD_NM_ADDR']].drop_duplicates()
null_places

                   VISIT_AREA_NM                     ROAD_NM_ADDR
11538                       마이온홈        제주특별자치도 제주시 애월읍 애원로 132-6
11592                       1943              제주특별자치도 제주시 연동7길 38
11667                    제주향토음식점                   공항로2 제주국제공항 4층
12164                 플레이팅 제주공항점                     제주시 공항로 2 2층
13080                파노라마 게스트하우스                월령3길 28-5 파노라마 제주
...                          ...                              ...
44919                        선 4                         제주시 공항로2
45255  서귀중앙초등학교(중앙동 도시재생 예체능 축제)             제주특별자치도 서귀포시 동문동로 54
45332                    대정농협주유소       제주특별자치도 서귀포시 대정읍 일주서로 2545
45568                   아사라 베이커리                  제주시 선사로2길 37 1층
45661                        벨루가  제주특별자치도 서귀포시 대정읍 영락하동로85번길 41-1

[502 rows x 2 columns]

In [110]:
columns_to_check = ['X_COORD', 'Y_COORD']
null_rows = tn_visit_area_info[tn_visit_area_info[columns_to_check].isnull().any(axis=1)]

null_places = null_rows[['VISIT_AREA_NM', 'ROAD_NM_ADDR']].drop_duplicates()
null_places

                   VISIT_AREA_NM                     ROAD_NM_ADDR
11538                       마이온홈        제주특별자치도 제주시 애월읍 애원로 132-6
11592                       1943              제주특별자치도 제주시 연동7길 38
11667                    제주향토음식점                   공항로2 제주국제공항 4층
12164                 플레이팅 제주공항점                     제주시 공항로 2 2층
13080                파노라마 게스트하우스                월령3길 28-5 파노라마 제주
...                          ...                              ...
44919                        선 4                         제주시 공항로2
45255  서귀중앙초등학교(중앙동 도시재생 예체능 축제)             제주특별자치도 서귀포시 동문동로 54
45332                    대정농협주유소       제주특별자치도 서귀포시 대정읍 일주서로 2545
45568                   아사라 베이커리                  제주시 선사로2길 37 1층
45661                        벨루가  제주특별자치도 서귀포시 대정읍 영락하동로85번길 41-1

[537 rows x 2 columns]

In [71]:
# 외부 API 활용 NULL X, Y COORD 채워넣기

import requests
import time

def get_coordinates(address, api_key="AIzaSyByYhrv3G7EyNjE3tDESg5qJp79H9aalDQ"):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {"address": address, "key": api_key}
    response = requests.get(base_url, params=params)
    if response.status_code == 200:
        results = response.json().get('results', [])
        if results:
            location = results[0]['geometry']['location']
            return location['lat'], location['lng']
    return None, None

# NULL 값이 있는 행만 필터링
missing_coords = tn_visit_area_info[tn_visit_area_info['X_COORD'].isnull() | tn_visit_area_info['Y_COORD'].isnull()]

# 좌표 채우기
for index, row in missing_coords.iterrows():
    address = row['ROAD_NM_ADDR']
    lat, lng = get_coordinates(address)
    if lat and lng:
        tn_visit_area_info.at[index, 'X_COORD'] = lat
        tn_visit_area_info.at[index, 'Y_COORD'] = lng
    time.sleep(0.1)  # API 호출 간격 조정

In [72]:
tn_visit_area_info.isnull().sum()

VISIT_AREA_ID            0
TRAVEL_ID                0
VISIT_ORDER              0
VISIT_AREA_NM            0
VISIT_START_YMD          0
VISIT_END_YMD            0
ROAD_NM_ADDR             0
X_COORD                  0
Y_COORD                  0
POI_ID                 670
POI_NM                 670
RESIDENCE_TIME_MIN       0
VISIT_AREA_TYPE_CD       0
REVISIT_YN               0
VISIT_CHC_REASON_CD      0
LODGING_TYPE_CD          0
DGSTFN                   0
REVISIT_INTENTION        0
RCMDTN_INTENTION         0
SGG_CD                   0
dtype: int64

In [77]:
visit_area_names = [
    "마이온홈", "1943", "제주향토음식점", "플레이팅 제주공항점", "파노라마 게스트하우스",
    "그랜드 하얏트 제주", "이마트 신제주점", "한라산 영실코스", "이마트 서귀포점",
    "꿀자락 제주", "글레이스 제주리조트", "향파정 항몽 유적지", "우무", "맨드롱하우스",
    "루나풀", "새벽 3시 4분에 오픈하는 도삭면", "단산", "혼인지", "제주 봄날", "살롱드탑차"
]

filtered_data = tn_visit_area_info[tn_visit_area_info['VISIT_AREA_NM'].isin(visit_area_names)]

filtered_data

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,X_COORD,Y_COORD,POI_ID,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
11538,2305190006,h_h000025,10,마이온홈,2023-05-19,2023-05-19,제주특별자치도 제주시 애월읍 애원로 132-6,33.453856,126.326131,NaN,NaN,90.0,24,N,2.0,3.0,4.0,4.0,4.0,5011025300.0
11592,2305150009,h_h000031,9,1943,2023-05-15,2023-05-15,제주특별자치도 제주시 연동7길 38,33.486581,126.490512,NaN,NaN,120.0,11,N,2.0,nan,5.0,5.0,5.0,50110.0
11667,2306040004,h_h000037,30,제주향토음식점,2023-06-04,2023-06-04,공항로2 제주국제공항 4층,33.507077,126.493431,NaN,NaN,60.0,9,N,9.0,nan,3.0,3.0,3.0,5011010900.0
12162,2305240006,h_h000076,12,그랜드 하얏트 제주,2023-05-24,2023-05-25,제주특별자치도 제주시 노연로 12,33.485242,126.481411,POI01000000D0FWO8,그랜드하얏트제주,150.0,24,N,2.0,1.0,5.0,5.0,5.0,nan
12164,2305250002,h_h000076,14,플레이팅 제주공항점,2023-05-25,2023-05-25,제주시 공항로 2 2층,33.507781,126.493133,NaN,NaN,30.0,11,N,6.0,nan,3.0,3.0,3.0,5011012200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45279,2309160004,h_h006477,4,이마트 서귀포점,2023-09-16,2023-09-16,제주특별자치도 서귀포시 일주동로 9209,33.248358,126.509207,POI01000TR041059V,이마트 서귀포점,60.0,4,Y,8.0,nan,5.0,5.0,5.0,nan
45470,2309160002,h_h006565,2,이마트 서귀포점,2023-09-16,2023-09-16,제주특별자치도 서귀포시 일주동로 9209,33.248358,126.509207,POI01000TR041059V,이마트 서귀포점,120.0,4,Y,7.0,nan,5.0,5.0,5.0,nan
45565,2309170007,h_h006587,6,이마트 서귀포점,2023-09-17,2023-09-17,제주특별자치도 서귀포시 일주동로 9209,33.248358,126.509207,POI01000TR041059V,이마트 서귀포점,30.0,4,Y,8.0,nan,5.0,5.0,5.0,nan
45812,2309160007,h_h006679,6,이마트 서귀포점,2023-09-16,2023-09-16,제주특별자치도 서귀포시 일주동로 9209,33.248358,126.509207,POI01000TR041059V,이마트 서귀포점,60.0,10,Y,9.0,nan,4.0,4.0,4.0,nan
45970,2309190005,h_h006749,5,이마트 서귀포점,2023-09-19,2023-09-19,제주특별자치도 서귀포시 일주동로 9209,33.248358,126.509207,POI01000TR041059V,이마트 서귀포점,120.0,4,Y,7.0,nan,4.0,5.0,3.0,nan

In [80]:
filtered_columns = ['VISIT_AREA_NM', 'ROAD_NM_ADDR', 'X_COORD', 'Y_COORD']
filtered_result = filtered_data[filtered_columns]
filtered_result

      VISIT_AREA_NM               ROAD_NM_ADDR    X_COORD     Y_COORD
11538          마이온홈  제주특별자치도 제주시 애월읍 애원로 132-6  33.453856  126.326131
11592          1943        제주특별자치도 제주시 연동7길 38  33.486581  126.490512
11667       제주향토음식점             공항로2 제주국제공항 4층  33.507077  126.493431
12162    그랜드 하얏트 제주         제주특별자치도 제주시 노연로 12  33.485242  126.481411
12164    플레이팅 제주공항점               제주시 공항로 2 2층  33.507781  126.493133
...             ...                        ...        ...         ...
45279      이마트 서귀포점     제주특별자치도 서귀포시 일주동로 9209  33.248358  126.509207
45470      이마트 서귀포점     제주특별자치도 서귀포시 일주동로 9209  33.248358  126.509207
45565      이마트 서귀포점     제주특별자치도 서귀포시 일주동로 9209  33.248358  126.509207
45812      이마트 서귀포점     제주특별자치도 서귀포시 일주동로 9209  33.248358  126.509207
45970      이마트 서귀포점     제주특별자치도 서귀포시 일주동로 9209  33.248358  126.509207

[143 rows x 4 columns]

In [76]:
invalid_coords = tn_visit_area_info[(tn_visit_area_info['X_COORD'] < 33) | (tn_visit_area_info['X_COORD'] > 34) |
                      (tn_visit_area_info['Y_COORD'] < 126) | (tn_visit_area_info['Y_COORD'] > 127)]
print(invalid_coords)

# X와 Y가 뒤바뀐 경우 수정
for index in invalid_coords.index:
    x = tn_visit_area_info.at[index, 'X_COORD']
    y = tn_visit_area_info.at[index, 'Y_COORD']
    tn_visit_area_info.at[index, 'X_COORD'] = y
    tn_visit_area_info.at[index, 'Y_COORD'] = x

      VISIT_AREA_ID  TRAVEL_ID  VISIT_ORDER VISIT_AREA_NM VISIT_START_YMD  \
2414     2307010002  e_e004090            2       제주 국제공항      2023-07-01
2711     2307070002  e_e004808            2       제주 국제공항      2023-07-07
2976     2307220006  e_e005480            2       제주 국제공항      2023-07-22
3050     2308030006  e_e005858           24       제주 국제공항      2023-08-03
11087    2308280003  g_g005682            3    제주원 렌터카 본점      2023-08-28
...             ...        ...          ...           ...             ...
45999    2309230003  h_h006872            3   항파두리 항몽 유적지      2023-09-23
46000    2309230004  h_h006872            4          소길별하      2023-09-23
46004    2309220002  h_h006874            2          꼬스뗀뇨      2023-09-22
46005    2309220003  h_h006874            3     마이 피기 팬트리      2023-09-22
46007    2309220005  h_h006874            5    민경이네어등포해녀촌      2023-09-22

      VISIT_END_YMD                 ROAD_NM_ADDR     X_COORD    Y_COORD  \
2414     2023-07-01            제주특별자치도 제주시 공항로 2  126.492769  33.507079
2711     2023-07-07            제주특별자치도 제주시 공항로 2  126.492769  33.507079
2976     2023-07-22            제주특별자치도 제주시 공항로 2  126.492769  33.507079
3050     2023-08-03            제주특별자치도 제주시 공항로 2  126.492769  33.507079
11087    2023-08-28         제주특별자치도 제주시 용해로 58-7  126.502477  33.511763
...             ...                          ...         ...        ...
45999    2023-09-23     제주특별자치도 제주시 애월읍 항파두리로 50  126.407923  33.452748
46000    2023-09-23   제주특별자치도 제주시 애월읍 소길남길 34-37  126.375776  33.429839
46004    2023-09-22  제주특별자치도 제주시 구좌읍 해맞이해안로 2080  126.905244  33.509868
46005    2023-09-22      제주특별자치도 제주시 구좌읍 하도13길 6  126.888132  33.508700
46007    2023-09-22   제주특별자치도 제주시 구좌읍 해맞이해안로 830  126.825773  33.553735

                  POI_ID      POI_NM  RESIDENCE_TIME_MIN VISIT_AREA_TYPE_CD  \
2414   POI01000TR024286V      제주국제공항                30.0                  9
2711   POI01000TR024286V      제주국제공항                30.0                  9
2976   POI01000TR024286V      제주국제공항                30.0                  9
3050   POI01000TR024286V      제주국제공항                60.0                  9
11087  POI01000TR007093V   제주원렌트카 본점                30.0                  9
...                  ...         ...                 ...                ...
45999  POI01000TR003745V  항파두리 항몽유적지                30.0                  2
46000  POI01000TR005834V        소길별하                60.0                 12
46004  POI01000TR019557V        꼬스뗀뇨                60.0                  3
46005  POI01000TR003070V     마이피기팬트리                30.0                 10
46007  POI01000TR017746V  민경이네어등포해녀촌                30.0                 11

      REVISIT_YN VISIT_CHC_REASON_CD LODGING_TYPE_CD  DGSTFN  \
2414           Y                 6.0             nan     4.0
2711           Y                 6.0             nan     4.0
2976           Y                 6.0             nan     4.0
3050           Y                 6.0             nan     5.0
11087          N                 2.0             nan     4.0
...          ...                 ...             ...     ...
45999          N                 1.0             nan     4.0
46000          N                 1.0             nan     4.0
46004          N                 1.0             nan     3.0
46005          N                 2.0             nan     4.0
46007          N                 2.0             nan     4.0

       REVISIT_INTENTION  RCMDTN_INTENTION SGG_CD
2414                 3.0               3.0    nan
2711                 4.0               4.0    nan
2976                 5.0               4.0    nan
3050                 5.0               5.0    nan
11087                4.0               4.0    nan
...                  ...               ...    ...
45999                4.0               4.0    nan
46000                4.0               4.0    nan
46004                2.0               2.0    nan
46005                4.0               4.0    nan
46007                4.0               4.0    nan

[22741 rows x 20 columns]

In [79]:
tn_visit_area_info.isnull().sum()

VISIT_AREA_ID            0
TRAVEL_ID                0
VISIT_ORDER              0
VISIT_AREA_NM            0
VISIT_START_YMD          0
VISIT_END_YMD            0
ROAD_NM_ADDR             0
X_COORD                  0
Y_COORD                  0
POI_ID                 670
POI_NM                 670
RESIDENCE_TIME_MIN       0
VISIT_AREA_TYPE_CD       0
REVISIT_YN               0
VISIT_CHC_REASON_CD      0
LODGING_TYPE_CD          0
DGSTFN                   0
REVISIT_INTENTION        0
RCMDTN_INTENTION         0
SGG_CD                   0
dtype: int64

In [81]:
# POI_NM, POI_ID NULL값 채우기

null_poi_data = tn_visit_area_info[
    tn_visit_area_info_c['POI_ID'].isnull() | tn_visit_area_info_c['POI_NM'].isnull()
]

null_poi_data

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,X_COORD,Y_COORD,POI_ID,POI_NM,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD
11538,2305190006,h_h000025,10,마이온홈,2023-05-19,2023-05-19,제주특별자치도 제주시 애월읍 애원로 132-6,33.453856,126.326131,NaN,NaN,90.0,24,N,2.0,3.0,4.0,4.0,4.0,5011025300.0
11592,2305150009,h_h000031,9,1943,2023-05-15,2023-05-15,제주특별자치도 제주시 연동7길 38,33.486581,126.490512,NaN,NaN,120.0,11,N,2.0,nan,5.0,5.0,5.0,50110.0
11667,2306040004,h_h000037,30,제주향토음식점,2023-06-04,2023-06-04,공항로2 제주국제공항 4층,33.507077,126.493431,NaN,NaN,60.0,9,N,9.0,nan,3.0,3.0,3.0,5011010900.0
12164,2305250002,h_h000076,14,플레이팅 제주공항점,2023-05-25,2023-05-25,제주시 공항로 2 2층,33.507781,126.493133,NaN,NaN,30.0,11,N,6.0,nan,3.0,3.0,3.0,5011012200.0
13080,2305230002,h_h000168,8,파노라마 게스트하우스,2023-05-23,2023-05-24,월령3길 28-5 파노라마 제주,33.377927,126.217002,NaN,NaN,300.0,24,N,1.0,7.0,4.0,3.0,3.0,5011025032.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44919,2309150007,h_h006338,14,선 4,2023-09-15,2023-09-15,제주시 공항로2,33.507781,126.493133,NaN,NaN,30.0,9,N,9.0,nan,2.0,2.0,2.0,5011010100.0
45255,2309160003,h_h006470,3,서귀중앙초등학교(중앙동 도시재생 예체능 축제),2023-09-16,2023-09-16,제주특별자치도 서귀포시 동문동로 54,33.252816,126.563777,NaN,NaN,90.0,8,N,10.0,nan,4.0,3.0,3.0,5013010100.0
45332,2309160002,h_h006500,2,대정농협주유소,2023-09-16,2023-09-16,제주특별자치도 서귀포시 대정읍 일주서로 2545,33.227566,126.258419,NaN,NaN,30.0,9,Y,6.0,nan,5.0,5.0,5.0,5011025025.0
45568,2309180002,h_h006587,10,아사라 베이커리,2023-09-18,2023-09-18,제주시 선사로2길 37 1층,33.524872,126.589548,NaN,NaN,60.0,11,N,2.0,nan,5.0,4.0,5.0,5011011300.0
45661,2309150005,h_h006629,5,벨루가,2023-09-15,2023-09-16,제주특별자치도 서귀포시 대정읍 영락하동로85번길 41-1,33.252627,126.201428,NaN,NaN,180.0,24,N,2.0,3.0,5.0,5.0,5.0,5013010500.0

In [93]:
null_poi_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 670 entries, 11538 to 45661
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   VISIT_AREA_ID        670 non-null    object
 1   TRAVEL_ID            670 non-null    object
 2   VISIT_ORDER          670 non-null    int64
 3   VISIT_AREA_NM        670 non-null    object
 4   VISIT_START_YMD      670 non-null    datetime64[ns]
 5   VISIT_END_YMD        670 non-null    datetime64[ns]
 6   ROAD_NM_ADDR         670 non-null    object
 7   X_COORD              670 non-null    float64
 8   Y_COORD              670 non-null    float64
 9   POI_ID               0 non-null      object
 10  POI_NM               0 non-null      object
 11  RESIDENCE_TIME_MIN   670 non-null    float64
 12  VISIT_AREA_TYPE_CD   670 non-null    object
 13  REVISIT_YN           670 non-null    object
 14  VISIT_CHC_REASON_CD  670 non-null    object
 15  LODGING_TYPE_CD      670 non-null    object
 16  DGSTFN               670 non-null    float64
 17  REVISIT_INTENTION    670 non-null    float64
 18  RCMDTN_INTENTION     670 non-null    float64
 19  SGG_CD               670 non-null    object
dtypes: datetime64[ns](2), float64(6), int64(1), object(11)
memory usage: 109.9+ KB

In [92]:
file_path = r"E:\AI_HUB\data\Other\메타데이터\tn_poi_master_POIMaster_jeju.csv"

tn_poi_master_POIMaster_jeju = pd.read_csv(file_path)

tn_poi_master_POIMaster_jeju.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125455 entries, 0 to 125454
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   POI_ID        125455 non-null  object
 1   POI_NM        125455 non-null  object
 2   SGG_CD        125455 non-null  object
 3   ROAD_NM_ADDR  125455 non-null  object
 4   X_COORD       125455 non-null  float64
 5   Y_COORD       125455 non-null  float64
 6   ROAD_NM_CD    125455 non-null  object
 7   LOTNO_CD      125455 non-null  object
dtypes: float64(2), object(6)
memory usage: 7.7+ MB

In [99]:
# POI NM, POI ID 채워넣기

poi_subset = tn_poi_master_POIMaster_jeju[['POI_ID', 'POI_NM', 'ROAD_NM_ADDR']]

# ROAD_NM_ADDR를 기준으로 병합
tn_visit_area_info = tn_visit_area_info.merge(
    poi_subset,
    on='ROAD_NM_ADDR',
    how='left',
    suffixes=('', '_poi')  # 새로 병합된 열에 접미사 추가
)

# POI_ID와 POI_NM이 NULL인 값 채우기
tn_visit_area_info['POI_ID'] = tn_visit_area_info['POI_ID'].fillna(tn_visit_area_info['POI_ID_poi'])
tn_visit_area_info['POI_NM'] = tn_visit_area_info['POI_NM'].fillna(tn_visit_area_info['POI_NM_poi'])

# 불필요한 병합 열 삭제
tn_visit_area_info = tn_visit_area_info.drop(columns=['POI_ID_poi', 'POI_NM_poi'])

KeyboardInterrupt:

In [97]:
tn_visit_area_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811141 entries, 0 to 811140
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   VISIT_AREA_ID        811141 non-null  object
 1   TRAVEL_ID            811141 non-null  object
 2   VISIT_ORDER          811141 non-null  int64
 3   VISIT_AREA_NM        811141 non-null  object
 4   VISIT_START_YMD      811141 non-null  datetime64[ns]
 5   VISIT_END_YMD        811141 non-null  datetime64[ns]
 6   ROAD_NM_ADDR         811141 non-null  object
 7   X_COORD              811141 non-null  float64
 8   Y_COORD              811141 non-null  float64
 9   POI_ID               810996 non-null  object
 10  POI_NM               810996 non-null  object
 11  RESIDENCE_TIME_MIN   811141 non-null  float64
 12  VISIT_AREA_TYPE_CD   811141 non-null  object
 13  REVISIT_YN           811141 non-null  object
 14  VISIT_CHC_REASON_CD  811141 non-null  object
 15  LODGING_TYPE_CD      811141 non-null  object
 16  DGSTFN               811141 non-null  float64
 17  REVISIT_INTENTION    811141 non-null  float64
 18  RCMDTN_INTENTION     811141 non-null  float64
 19  SGG_CD               811141 non-null  object
dtypes: datetime64[ns](2), float64(6), int64(1), object(11)
memory usage: 123.8+ MB

In [17]:
unique_travelers = tn_visit_area_info['TRAVEL_ID'].nunique()
print(f"고유한 여행 수: {unique_travelers}")

고유한 여행 수: 2560

In [23]:
visits_per_traveler = tn_visit_area_info.groupby('TRAVEL_ID').size()
visits_per_traveler.describe()

count    2560.000000
mean       17.972266
std        10.139146
min         3.000000
25%         9.000000
50%        16.000000
75%        25.000000
max        70.000000
dtype: float64

In [ ]:
import shutil

# 파일 저장 경로
local_path = r"E:\AI_HUB\data\Training\labeled_data\TL_csv\cleaned_codeb_data.csv"
cleaned_codeb_data.to_csv(local_path, index=False, encoding='utf-8-sig')

# 파일 저장 확인
print(f"로컬 경로에 파일 저장 완료: {local_path}")